"""Shorthand methods on :class:`GeometricHEG` for chained Conway operators.

Importing this module attaches one method per factory in :mod:`.factories`
to :class:`GeometricHEG`, enabling fluent chains like::

    G.ambo().dual().truncate(0.4).dual()

Each method instantiates the operator with the factory parameters and applies
it to the graph, forwarding the remaining keyword arguments to
:meth:`TopologicalConwayOperator.__call__`. Like the operator call itself,
each method leaves the input untouched and returns a new graph by default;
pass ``inplace=True`` to mutate the graph and return it.

``faces`` may be either a set of :class:`Face` or a callable
``face -> bool`` used as a face filter.

The shorthand methods are generated by :func:`_shorthand` from the factory
functions. Each generated method gets a synthesized :class:`inspect.Signature`
that combines the factory's parameters with the four standard
:meth:`TopologicalConwayOperator.__call__` kwargs, so ``help(G.truncate)``
and Jupyter's ``G.truncate?`` show the full signature.
"""

from __future__ import annotations

import inspect

from ..half import GeometricHEG
from . import factories

# The four kwargs that get forwarded to TopologicalConwayOperator.__call__.
_CALL_PARAMS = (
    inspect.Parameter(
        "faces",
        inspect.Parameter.KEYWORD_ONLY,
        default=None,
        annotation="set[Face] | Callable[[Face], bool] | None",
    ),
    inspect.Parameter("delete_on_border", inspect.Parameter.KEYWORD_ONLY, default=True, annotation=bool),
    inspect.Parameter("delete_inner_border", inspect.Parameter.KEYWORD_ONLY, default=False, annotation=bool),
    inspect.Parameter("inplace", inspect.Parameter.KEYWORD_ONLY, default=False, annotation=bool),
)
_CALL_PARAM_NAMES = frozenset(p.name for p in _CALL_PARAMS)


def _shorthand(factory):
    """Build a ``GeometricHEG`` method that applies ``factory(...)`` to ``self``.

    The returned method exposes a synthesized signature ``(self, *factory_params,
    *, faces=None, delete_on_border=True, delete_inner_border=False,
    inplace=False)`` and the factory's docstring, so it is discoverable via
    ``help()`` and ``?`` even though the method body is only one line.
    """

    def method(self, *args, **kwargs):
        call_kwargs = {k: kwargs.pop(k) for k in _CALL_PARAM_NAMES if k in kwargs}
        return factory(*args, **kwargs)(self, **call_kwargs)

    factory_params = list(inspect.signature(factory).parameters.values())
    method.__signature__ = inspect.Signature(  # type: ignore[attr-defined]
        parameters=[
            inspect.Parameter("self", inspect.Parameter.POSITIONAL_OR_KEYWORD),
            *factory_params,
            *_CALL_PARAMS,
        ],
        return_annotation="GeometricHEG",
    )
    method.__name__ = factory.__name__.removesuffix("_graph")
    method.__qualname__ = f"GeometricHEG.{method.__name__}"
    method.__doc__ = f"Shorthand for ``{factory.__name__}(...)(self, ...)``.\n\n" f"{(factory.__doc__ or '').strip()}"
    return method


_FACTORIES = [getattr(factories, n) for n in dir(factories) if n.endswith("_graph")]

for _factory in _FACTORIES:
    setattr(GeometricHEG, _factory.__name__.removesuffix("_graph"), _shorthand(_factory))
